# MySQL.  Versions 3.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: postgresql
  encoding: utf8
  database: portal_engine
  pool: 10
  username: livia
  password: livia

production:
  adapter: postgresql
  encoding: utf8
  database: portal_engine
  pool: 10
  username: livia
  password: livia

test:
  adapter: postgresql
  encoding: utf8
  database: portal_engine
  pool: 10
  username: livia
  password: livia

